name: "Enable systemd-resolved"
description: "Use systemd-resolved stub resolver and manage resolv.conf"
commands:
  - 'sudo systemctl enable systemd-resolved.service'
  - 'sudo systemctl start systemd-resolved.service'
  - 'sudo ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf'
