name: caddy-internal
podman:
  user: root
  network: ipvlan-l2
composition:
  ingress:
    internal:
      base:
        source: caddy-internal/config/Caddyfile
        destination: /srv/caddy/internal/Caddyfile
  container:
    named_volumes:
      - name: config
        host_path: /srv/caddy/internal/config
        mount_path: /config
      - name: data
        host_path: /srv/caddy/internal/data
        mount_path: /data
      - name: host-certs
        host_path: /etc/ssl/certs
        mount_path: /etc/ssl/certs
        mode: ro
        shared: true
    mounted_files:
      - host_path: /srv/caddy/internal/Caddyfile
        mount_path: /etc/caddy/Caddyfile
