name: blocky-common
composition:
  container:
    named_volumes:
      - name: host-certs
        host_path: /etc/ssl/certs
        mount_path: /etc/ssl/certs
        mode: ro
        shared: true
    mounted_files:
      - host_path: /srv/blocky/config.yml
        mount_path: /app/config.yml
        mode: ro
