name: chrony-a
systemd:
  network: service-32
apply:
  config_change_restart_unit: chrony.service
composition:
  config:
    - source:
        template: chrony-common/config/chrony.conf.j2
        variables:
          bind_ip: '%%network.services.chrony-a.address | strip_cidr%%'
          peer_ip: '%%network.services.chrony-b.address | strip_cidr%%'
          stratum: 10
      destination: /etc/chrony/chrony.conf
