name: chrony-a
systemd:
  network: service-32
composition:
  config:
    - source:
        template: chrony-common/config/chrony.conf.j2
        variables:
          bind_ip: '%%network.services.chrony-a.address%%'
          peer_ip: '%%network.services.chrony-b.address%%'
          stratum: 10
      destination: /etc/chrony/chrony.conf
