name: phobos
physical_device: enp0s31f6
composition:
  include:
    - common
  config:
    - source:
        template: phobos/systemd-networkd/10-enp0s31f6.network.j2
        variables: {}
      destination: /etc/systemd/network/10-enp0s31f6.network
    - source: phobos/systemd-networkd/20-ipvlan-l2.netdev
      destination: /etc/systemd/network/20-ipvlan-l2.netdev
    - source:
        template: phobos/systemd-networkd/21-ipvlan-l2.network.j2
        variables: {}
      destination: /etc/systemd/network/21-ipvlan-l2.network
    - destination: /etc/systemd/network/21-ipvlan-l2.network.d/
    - source: phobos/systemd-networkd/30-enp0s31f6.100.netdev
      destination: /etc/systemd/network/30-enp0s31f6.100.netdev
    - source:
        template: phobos/systemd-networkd/31-enp0s31f6.100.network.j2
        variables: {}
      destination: /etc/systemd/network/31-enp0s31f6.100.network
    - source: phobos/systemd-networkd/40-ipvlan-l2.100.netdev
      destination: /etc/systemd/network/40-ipvlan-l2.100.netdev
    - source:
        template: phobos/systemd-networkd/41-ipvlan-l2.100.network.j2
        variables: {}
      destination: /etc/systemd/network/41-ipvlan-l2.100.network
    - destination: /etc/systemd/network/41-ipvlan-l2.100.network.d/
    - source: phobos/tools/vault-unseal.sh
      destination: /usr/local/lib/abhaile/tools/vault-unseal.sh
  systemd:
    - source:
        template: phobos/systemd/abhaile-vault-unseal.service.j2
        variables:
          vault_addr: '%%network.services.vault.address%%'
      destination: /etc/systemd/system/abhaile-vault-unseal.service
      enable: true
      start: true
  software:
    builds:
      - gasket-dkms
    commands:
      - ddclient
      - coral-tpu-modules
      - coral-tpu-udev
    downloads: []
    packages:
      - ddclient
  user_management:
    groups: {}
    sudoers: []
    users:
      abhaile:
        additional_groups:
          - sudo
          - apex
