name: coredns-common
composition:
  config:
    - source: coredns-common/systemd/coredns-zones.path
      destination: /etc/systemd/system/coredns-zones.path
    - source: coredns-common/systemd/coredns-zones.service
      destination: /etc/systemd/system/coredns-zones.service
    - source:
        template: coredns-common/config/zones/zone.zone.j2
        variables: {}
      destination: /etc/coredns/zones/DYNAMIC_ZONE_PLACEHOLDER
