name: coredns-clean
type: host
mode: ''
network: service-32
include:
  - coredns-common
  - coredns-omada
config:
  - source:
      template: coredns-common/config/Corefile.j2
      variables:
        bind_ip: "%%services.coredns-clean.address | strip_cidr%%"
        forward_to: 9.9.9.9 149.112.112.112 1.1.1.1 1.0.0.1
        omada_ip: "%%services.omada-controller.address | strip_cidr%%"
        dmz_caddy_ip: "%%services.caddy-dmz.address | strip_cidr%%"
    destination: /etc/coredns/Corefile
