name: coredns-filtered
systemd:
  network: service-32
composition:
  include:
    - coredns-common
    - coredns-omada
  config:
    - source:
        template: coredns-common/config/Corefile.j2
        variables:
          bind_ip: '%%network.services.coredns-filtered.address | strip_cidr%%'
          forward_to: '%%network.services.blocky.address | strip_cidr%%:8053'
          omada_ip: '%%network.services.omada-controller.address | strip_cidr%%'
          dmz_caddy_ip: '%%network.services.caddy-dmz.address | strip_cidr%%'
      destination: /etc/coredns/Corefile
