name: coredns-a
systemd:
  network: service-32
apply:
  config_change_restart_unit: null
composition:
  include:
    - coredns-common
    - coredns-omada
  config:
    - source:
        template: coredns-common/config/Corefile.j2
        variables:
          bind_ip: '%%network.services.coredns-a.address | strip_cidr%%'
          filtered_forward_to: '%%network.services.blocky-a.address | strip_cidr%%:8053'
          dmz_caddy_ip: '%%network.services.caddy-dmz.address | strip_cidr%%'
      destination: /etc/coredns/Corefile
