name: vault
podman:
  user: root
  network: ipvlan-l2
composition:
  config:
    - source:
        template: vault/config/local.json.j2
        variables:
          listener_address: '%%network.services.vault.address%%'
          cluster_addr: '%%network.services.vault.address%%'
          api_addr: '%%network.services.vault.address%%'
      destination: /srv/vault/config/local.json
    - source: vault/config/vault.env
      destination: /srv/vault/vault.env
  ingress:
    internal:
      blocks:
        - vault/caddy/internal-ingress.txt
  container:
    named_volumes:
      - name: config
        host_path: /srv/vault/config
        mount_path: /vault/config
      - name: data
        host_path: /srv/vault/data
        mount_path: /vault/data
      - name: host-certs
        host_path: /etc/ssl/certs
        mount_path: /etc/ssl/certs
        mode: ro
        shared: true
