name: ddclient
systemd:
  network: host
composition:
  systemd:
    - source: ddclient/systemd/ddclient-conf.service
      destination: /etc/systemd/system/ddclient-conf.service
    - source: ddclient/systemd/ddclient-conf.path
      destination: /etc/systemd/system/ddclient-conf.path
      enable: true
      start: true
  vault_agent:
    templates:
      - source: ddclient/templates/ddclient.conf.ctmpl
        out: ddclient.conf
        perms: '0640'
