ARG CADDY_VERSION

FROM docker.io/library/caddy:${CADDY_VERSION}-builder AS builder

RUN xcaddy build ${CADDY_VERSION}\
    --with github.com/caddy-dns/desec@822a6a2

FROM docker.io/library/caddy:${CADDY_VERSION}

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
