abhaile:
  - phobos:
      - abhaile-runner
      - ddclient
      - chrony-a
      - coredns-filtered
      - blocky
      - caddy-internal
      - caddy-dmz
      - vault
      - vault-agent
      - authelia
      - omada-controller
  - deimos:
      - abhaile-runner
      - chrony-b
      - coredns-clean
      - vault-agent
