abhaile:
  - phobos:
      - ddclient
      - chrony-a
      - coredns-a
      - blocky-a
      - caddy-internal
      - caddy-dmz
      - vault
      - vault-agent
      - authelia
      - omada-controller
  - deimos:
      - chrony-b
      - coredns-b
      - blocky-b
      - vault-agent
