vlans:
  services:
    id: 20
    cidr: 172.20.20.0/24
    gateway: 172.20.20.1
    ipvlanl2_range: 172.20.20.200-172.20.20.254
  dmz:
    id: 100
    cidr: 172.20.100.0/24
    gateway: 172.20.100.1
    ipvlanl2_range: 172.20.100.200-172.20.100.254
dns:
  zones:
    - name: abhaile.dedyn.io.
      provider:
        type: external
        name: desec.io
    - name: svc.abhaile.home.arpa.
      provider:
        type: internal
        name: coredns-common
      serial:
        date: 20260208
        counter: 00
        content_hash: 1f30b95d34bed91f57d99bb18591d72c4efe7a9cc648ee4d388959b1dcc71012
    - name: abhaile.home.arpa.
      provider:
        type: internal
        name: coredns-common
      serial:
        date: 20260208
        counter: 00
        content_hash: 55f4784e31149cd2580b7666bff64abf49838c2410cdd75e76234babb9bc1748
    - name: 20.20.172.in-addr.arpa.
      provider:
        type: internal
        name: coredns-common
      serial:
        date: 20260208
        counter: 00
        content_hash: 771916af8f56aa367ad39d1618e5d79a21ea5b706a69939173771bac5e1c0fe9
    - name: 100.20.172.in-addr.arpa.
      provider:
        type: internal
        name: coredns-common
      serial:
        date: 20260208
        counter: 00
        content_hash: 4b0d98ea561ac53aa7a52f0261bb9b23cca2ea4455920387f39097d0c47e073b
hosts:
  phobos:
    interfaces:
      enp0s31f6:
        address: 172.20.20.10/24
        vlan: services
      ipvlan-l2:
        address: 172.20.20.20/32
        vlan: services
      enp0s31f6.100:
        address: 172.20.100.10/24
        vlan: dmz
      ipvlan-l2.100:
        address: 172.20.100.20/32
        vlan: dmz
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: phobos
            rdata: "%%network.hosts.phobos.interfaces.enp0s31f6.address | strip_cidr%%"
            ptr: true
          - type: a
            name: dmz
            rdata: "%%network.hosts.phobos.interfaces.enp0s31f6.100.address | strip_cidr%%"
            ptr: true
      - zone: abhaile.home.arpa.
        records:
          - type: cname
            name: phobos
            rdata: phobos.svc.abhaile.home.arpa.
  deimos:
    interfaces:
      enp0s31f6:
        address: 172.20.20.11/24
        vlan: services
      ipvlan-l2:
        address: 172.20.20.21/32
        vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: deimos
            rdata: "%%network.hosts.deimos.interfaces.enp0s31f6.address | strip_cidr%%"
            ptr: true
      - zone: abhaile.home.arpa.
        records:
          - type: cname
            name: deimos
            rdata: deimos.svc.abhaile.home.arpa.
services:
  caddy-dmz:
    address: 172.20.100.200/32
    vlan: dmz
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: caddy-dmz
            rdata: "%%network.services.caddy-dmz.address | strip_cidr%%"
            ptr: true
      - zone: abhaile.dedyn.io.
        records:
          - type: a
            name: "*"
            rdata: "%%network.services.caddy-dmz.address | strip_cidr%%"
  caddy-internal:
    address: 172.20.20.200/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: caddy-internal
            rdata: "%%network.services.caddy-internal.address | strip_cidr%%"
            ptr: true
      - zone: abhaile.home.arpa.
        records:
          - type: cname
            name: caddy
            rdata: caddy-internal.svc.abhaile.home.arpa.
          - type: cname
            name: ca
            rdata: caddy.abhaile.home.arpa.
          - type: cname
            name: test
            rdata: caddy.abhaile.home.arpa.
  authelia:
    address: 172.20.20.201/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: authelia
            rdata: "%%network.services.authelia.address | strip_cidr%%"
            ptr: true
      - zone: abhaile.home.arpa.
        records:
          - type: cname
            name: authelia
            rdata: caddy.abhaile.home.arpa.
          - type: cname
            name: login
            rdata: authelia.abhaile.home.arpa.
  homepage:
    address: 172.20.20.202/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: homepage
            rdata: "%%network.services.homepage.address | strip_cidr%%"
            ptr: true
  netbox:
    address: 172.20.20.203/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: netbox
            rdata: "%%network.services.netbox.address | strip_cidr%%"
            ptr: true
  vault:
    address: 172.20.20.204/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: vault
            rdata: "%%network.services.vault.address | strip_cidr%%"
            ptr: true
      - zone: abhaile.home.arpa.
        records:
          - type: cname
            name: vault
            rdata: caddy.abhaile.home.arpa.
  vaultwarden:
    address: 172.20.20.205/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: vaultwarden
            rdata: "%%network.services.vaultwarden.address | strip_cidr%%"
            ptr: true
  postfix:
    address: 172.20.20.206/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: postfix
            rdata: "%%network.services.postfix.address | strip_cidr%%"
            ptr: true
  crowdsec:
    address: 172.20.20.207/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: crowdsec
            rdata: "%%network.services.crowdsec.address | strip_cidr%%"
            ptr: true
  prometheus:
    address: 172.20.20.210/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: prometheus
            rdata: "%%network.services.prometheus.address | strip_cidr%%"
            ptr: true
  alertmanager:
    address: 172.20.20.211/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: alertmanager
            rdata: "%%network.services.alertmanager.address | strip_cidr%%"
            ptr: true
  grafana:
    address: 172.20.20.212/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: grafana
            rdata: "%%network.services.grafana.address | strip_cidr%%"
            ptr: true
  blackbox-exporter:
    address: 172.20.20.213/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: blackbox-exporter
            rdata: "%%network.services.blackbox-exporter.address | strip_cidr%%"
            ptr: true
  snmp-exporter:
    address: 172.20.20.214/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: snmp-exporter
            rdata: "%%network.services.snmp-exporter.address | strip_cidr%%"
            ptr: true
  uptime-kuma:
    address: 172.20.20.215/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: uptime-kuma
            rdata: "%%network.services.uptime-kuma.address | strip_cidr%%"
            ptr: true
  librespeed:
    address: 172.20.20.216/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: librespeed
            rdata: "%%network.services.librespeed.address | strip_cidr%%"
            ptr: true
  smokeping:
    address: 172.20.20.217/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: smokeping
            rdata: "%%network.services.smokeping.address | strip_cidr%%"
            ptr: true
  loki:
    address: 172.20.20.218/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: loki
            rdata: "%%network.services.loki.address | strip_cidr%%"
            ptr: true
  omada-controller:
    address: 172.20.20.220/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: omada-controller
            rdata: "%%network.services.omada-controller.address | strip_cidr%%"
            ptr: true
      - zone: abhaile.home.arpa.
        records:
          - type: cname
            name: omada
            rdata: caddy.abhaile.home.arpa.
  home-assistant:
    address: 172.20.20.221/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: home-assistant
            rdata: "%%network.services.home-assistant.address | strip_cidr%%"
            ptr: true
  mosquitto:
    address: 172.20.20.222/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: mosquitto
            rdata: "%%network.services.mosquitto.address | strip_cidr%%"
            ptr: true
  zigbee2mqtt:
    address: 172.20.20.223/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: zigbee2mqtt
            rdata: "%%network.services.zigbee2mqtt.address | strip_cidr%%"
            ptr: true
  esphome:
    address: 172.20.20.224/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: esphome
            rdata: "%%network.services.esphome.address | strip_cidr%%"
            ptr: true
  go2rtc:
    address: 172.20.20.225/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: go2rtc
            rdata: "%%network.services.go2rtc.address | strip_cidr%%"
            ptr: true
  frigate:
    address: 172.20.20.226/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: frigate
            rdata: "%%network.services.frigate.address | strip_cidr%%"
            ptr: true
  blocky:
    address: 172.20.20.234/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: blocky
            rdata: "%%network.services.blocky.address | strip_cidr%%"
            ptr: true
      - zone: abhaile.home.arpa.
        records:
          - type: cname
            name: blocky
            rdata: blocky.svc.abhaile.home.arpa.
  coredns-filtered:
    address: 172.20.20.235/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: coredns-filtered
            rdata: "%%network.services.coredns-filtered.address | strip_cidr%%"
            ptr: true
      - zone: abhaile.home.arpa.
        records:
          - type: cname
            name: ns1
            rdata: coredns-filtered.svc.abhaile.home.arpa.
  coredns-clean:
    address: 172.20.20.236/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: coredns-clean
            rdata: "%%network.services.coredns-clean.address | strip_cidr%%"
            ptr: true
      - zone: abhaile.home.arpa.
        records:
          - type: cname
            name: ns2
            rdata: coredns-clean.svc.abhaile.home.arpa.
  chrony-a:
    address: 172.20.20.237/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: chrony-a
            rdata: "%%network.services.chrony-a.address | strip_cidr%%"
            ptr: true
      - zone: abhaile.home.arpa.
        records:
          - type: cname
            name: ntp-a
            rdata: chrony-a.svc.abhaile.home.arpa.
  chrony-b:
    address: 172.20.20.238/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: chrony-b
            rdata: "%%network.services.chrony-b.address | strip_cidr%%"
            ptr: true
      - zone: abhaile.home.arpa.
        records:
          - type: cname
            name: ntp-b
            rdata: chrony-b.svc.abhaile.home.arpa.
  gluetun:
    address: 172.20.20.239/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: gluetun
            rdata: "%%network.services.gluetun.address | strip_cidr%%"
            ptr: true
  immich:
    address: 172.20.20.240/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: immich
            rdata: "%%network.services.immich.address | strip_cidr%%"
            ptr: true
  jellyfin:
    address: 172.20.20.241/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: jellyfin
            rdata: "%%network.services.jellyfin.address | strip_cidr%%"
            ptr: true
  tdarr:
    address: 172.20.20.242/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: tdarr
            rdata: "%%network.services.tdarr.address | strip_cidr%%"
            ptr: true
  radarr:
    address: 172.20.20.243/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: radarr
            rdata: "%%network.services.radarr.address | strip_cidr%%"
            ptr: true
  sonarr:
    address: 172.20.20.244/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: sonarr
            rdata: "%%network.services.sonarr.address | strip_cidr%%"
            ptr: true
  lidarr:
    address: 172.20.20.245/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: lidarr
            rdata: "%%network.services.lidarr.address | strip_cidr%%"
            ptr: true
  readarr:
    address: 172.20.20.246/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: readarr
            rdata: "%%network.services.readarr.address | strip_cidr%%"
            ptr: true
  bazarr:
    address: 172.20.20.247/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: bazarr
            rdata: "%%network.services.bazarr.address | strip_cidr%%"
            ptr: true
  prowlarr:
    address: 172.20.20.248/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: prowlarr
            rdata: "%%network.services.prowlarr.address | strip_cidr%%"
            ptr: true
  jellyseerr:
    address: 172.20.20.249/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: jellyseerr
            rdata: "%%network.services.jellyseerr.address | strip_cidr%%"
            ptr: true
  flaresolverr:
    address: 172.20.20.250/32
    vlan: services
    dns:
      - zone: svc.abhaile.home.arpa.
        records:
          - type: a
            name: flaresolverr
            rdata: "%%network.services.flaresolverr.address | strip_cidr%%"
            ptr: true
