name: blocky
podman:
  user: root
  network: ipvlan-l2
apply:
  config_change_restart_unit: blocky.service
composition:
  config:
    - source: blocky/config/config.yml
      destination: /srv/blocky/config.yml
  container:
    named_volumes:
      - name: host-certs
        host_path: /etc/ssl/certs
        mount_path: /etc/ssl/certs
        mode: ro
        shared: true
    mounted_files:
      - host_path: /srv/blocky/config.yml
        mount_path: /app/config.yml
        mode: ro
