name: blocky
podman:
  user: root
  network: ipvlan-l2
composition:
  config:
    - source: blocky/config/config.yml
      destination: /srv/blocky/config.yml
  container:
    named_volumes:
      - name: host-certs
        host: /etc/ssl/certs
        mount: /etc/ssl/certs
        mode: ro
        shared: true
    mounted_files:
      - host: /srv/blocky/config.yml
        mount: /app/config.yml
        mode: ro
