name: caddy-dmz
podman:
  user: root
  network: ipvlan-l2
composition:
  config:
    - source: caddy-dmz/build/Containerfile
      destination: /srv/build/caddy-desec/Containerfile
  systemd:
    - source: caddy-dmz/systemd/caddy-dns-desec.service
      destination: /etc/systemd/system/caddy-dns-desec.service
    - source: caddy-dmz/systemd/caddy-dns-desec.path
      destination: /etc/systemd/system/caddy-dns-desec.path
      enable: true
      start: true
  vault_agent:
    templates:
      - source: caddy-dmz/templates/caddy-dns-desec.env.ctmpl
        out: caddy-dns-desec.env
        perms: '0640'
  ingress:
    dmz:
      base:
        source: caddy-dmz/config/Caddyfile
        destination: /srv/caddy/dmz/Caddyfile
  container:
    named_volumes:
      - name: config
        host_path: /srv/caddy/dmz/config
        mount_path: /config
      - name: data
        host_path: /srv/caddy/dmz/data
        mount_path: /data
      - name: host-certs
        host_path: /etc/ssl/certs
        mount_path: /etc/ssl/certs
        mode: ro
        shared: true
    mounted_files:
      - host_path: /srv/caddy/dmz/Caddyfile
        mount_path: /etc/caddy/Caddyfile
