- name: install base host packages
  ansible.builtin.package:
    name:
      - python3
      - python3-venv
      - podman
      - crun
      - vim
      - git
      - vlan
      - curl
      - systemd-container
      - systemd-resolved
      - lm-sensors
      - sudo
      - unattended-upgrades
      - iperf
      - iperf3
      - chrony
      - unzip
      - age
      - jq
      - bind9-utils
    state: present
