name: blocky-b
podman:
  user: root
  network: ipvlan-l2
apply:
  config_change_restart_unit: blocky-b.service
composition:
  include:
    - blocky-common
  config:
    - source: blocky-common/config/config.yml
      destination: /srv/blocky/config.yml
